import Link from "next/link";
import { MagnifyingGlass, TrendUp, TrendDown, Minus } from "@phosphor-icons/react/dist/ssr";
import { requireActiveSubscription } from "@/lib/subscription-guard";
import { getStockList } from "@/lib/stocks";
import { searchStocks } from "@/lib/stock-search";
import { getQuote } from "@/lib/market-data";
import { getAnalystConsensus } from "@/lib/stocks";
import { Panel } from "@/components/Panel";
import { Disclaimer } from "@/components/Disclaimer";

const CONSENSUS_LABELS: Record<string, string> = {
  strong_buy: "Strong Buy",
  buy: "Buy",
  hold: "Hold",
  sell: "Sell",
  strong_sell: "Strong Sell",
};

function consensusColor(consensus: string) {
  if (consensus === "strong_buy" || consensus === "buy") return "text-positive";
  if (consensus === "sell" || consensus === "strong_sell") return "text-negative";
  return "text-muted";
}

function formatDelta(changePercent: number) {
  const sign = changePercent >= 0 ? "+" : "";
  return `${sign}${changePercent.toFixed(2)}%`;
}

export default async function StocksPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string }>;
}) {
  await requireActiveSubscription();

  const { q } = await searchParams;
  const query = q?.trim() ?? "";

  const stocks = query
    ? await Promise.all(
        (await searchStocks(query)).map(async (result) => {
          const quote = await getQuote(result.ticker, result.companyName, 100);
          const consensus = await getAnalystConsensus(result.ticker, quote.price);
          return {
            ticker: result.ticker,
            companyName: result.companyName,
            quote,
            ...consensus,
            totalAnalysts: consensus.buyCount + consensus.holdCount + consensus.sellCount,
          };
        }),
      )
    : await getStockList();

  const movers = !query
    ? {
        gainers: [...stocks].sort((a, b) => b.quote.changePercent - a.quote.changePercent).slice(0, 4),
        losers: [...stocks].sort((a, b) => a.quote.changePercent - b.quote.changePercent).slice(0, 4),
      }
    : null;

  return (
    <div className="mx-auto max-w-6xl px-6 py-8">
      <h1 className="text-2xl font-semibold">Stocks</h1>
      <p className="mt-1 text-sm text-muted">
        Search any ticker. Live prices with real third-party analyst consensus
        data — Buy/Hold/Sell counts and price targets as reported by analysts,
        not generated by DollarWatch.
      </p>

      <form method="GET" className="mt-6">
        <div className="relative max-w-sm">
          <MagnifyingGlass
            size={16}
            className="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-muted"
          />
          <input
            type="text"
            name="q"
            defaultValue={query}
            placeholder="Search ticker or company…"
            className="w-full rounded-md border border-panel-border bg-panel py-2 pr-3 pl-9 text-sm outline-none focus:border-accent"
          />
        </div>
      </form>

      {movers && (
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
          <Panel title="Top gainers">
            <div className="flex flex-col gap-2.5">
              {movers.gainers.map((stock) => (
                <Link
                  key={stock.ticker}
                  href={`/stocks/${stock.ticker}`}
                  className="flex items-center justify-between text-sm transition-colors hover:text-accent"
                >
                  <span className="font-mono font-medium">{stock.ticker}</span>
                  <span className="flex items-center gap-1 font-mono text-xs tabular-nums text-positive">
                    <TrendUp size={12} weight="bold" />
                    {formatDelta(stock.quote.changePercent)}
                  </span>
                </Link>
              ))}
            </div>
          </Panel>
          <Panel title="Top losers">
            <div className="flex flex-col gap-2.5">
              {movers.losers.map((stock) => (
                <Link
                  key={stock.ticker}
                  href={`/stocks/${stock.ticker}`}
                  className="flex items-center justify-between text-sm transition-colors hover:text-accent"
                >
                  <span className="font-mono font-medium">{stock.ticker}</span>
                  <span className="flex items-center gap-1 font-mono text-xs tabular-nums text-negative">
                    <TrendDown size={12} weight="bold" />
                    {formatDelta(stock.quote.changePercent)}
                  </span>
                </Link>
              ))}
            </div>
          </Panel>
        </div>
      )}

      <Panel title={query ? undefined : "All stocks"} className="mt-4">
        {stocks.length === 0 ? (
          <p className="text-sm text-muted">No matches for &ldquo;{query}&rdquo;.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-panel-border text-xs text-muted">
                  <th className="pb-2 pr-4 font-normal">Ticker</th>
                  <th className="pb-2 pr-4 font-normal">Company</th>
                  <th className="pb-2 pr-4 font-normal">Price</th>
                  <th className="pb-2 pr-4 font-normal">Change</th>
                  <th className="pb-2 pr-4 font-normal">Analyst consensus</th>
                  <th className="pb-2 pr-4 font-normal">Buy / Hold / Sell</th>
                  <th className="pb-2 font-normal">Avg. price target</th>
                </tr>
              </thead>
              <tbody>
                {stocks.map((stock) => {
                  const isPositive = stock.quote.changePercent >= 0;
                  const targetUpside =
                    ((stock.avgPriceTarget - stock.quote.price) / stock.quote.price) * 100;

                  return (
                    <tr key={stock.ticker} className="border-b border-panel-border/50">
                      <td className="py-2.5 pr-4 font-mono font-medium">
                        <Link href={`/stocks/${stock.ticker}`} className="hover:text-accent">
                          {stock.ticker}
                        </Link>
                      </td>
                      <td className="py-2.5 pr-4 text-muted">{stock.companyName}</td>
                      <td className="py-2.5 pr-4 font-mono tabular-nums">
                        ${stock.quote.price.toFixed(2)}
                      </td>
                      <td className="py-2.5 pr-4">
                        <span
                          className={`flex items-center gap-1 font-mono text-xs tabular-nums ${
                            isPositive ? "text-positive" : "text-negative"
                          }`}
                        >
                          {isPositive ? (
                            <TrendUp size={12} weight="bold" />
                          ) : (
                            <TrendDown size={12} weight="bold" />
                          )}
                          {formatDelta(stock.quote.changePercent)}
                        </span>
                      </td>
                      <td className="py-2.5 pr-4">
                        <span className={`font-medium ${consensusColor(stock.consensus)}`}>
                          {CONSENSUS_LABELS[stock.consensus]}
                        </span>
                      </td>
                      <td className="py-2.5 pr-4 text-xs text-muted">
                        <span className="text-positive">{stock.buyCount}</span>
                        {" / "}
                        <Minus size={10} className="inline" /> {stock.holdCount}
                        {" / "}
                        <span className="text-negative">{stock.sellCount}</span>
                      </td>
                      <td className="py-2.5 font-mono tabular-nums">
                        ${stock.avgPriceTarget.toFixed(2)}{" "}
                        <span className={targetUpside >= 0 ? "text-positive" : "text-negative"}>
                          ({targetUpside >= 0 ? "+" : ""}
                          {targetUpside.toFixed(1)}%)
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Panel>

      <div className="mt-6">
        <Disclaimer />
      </div>
    </div>
  );
}
